version: '3.9'
services:
  tui-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      - JAVA_OPTS=-XX:+UseZGC -Xmx2g
    restart: unless-stopped
