server:
  servlet:
    context-path: /pilotes/api

spring:
  datasource:
    url: jdbc:h2:mem:pilotesdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    show-sql: false
    properties:
      hibernate:
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.NoJtaPlatform
        format_sql: false
    open-in-view: false
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

pilotes:
  price-per-pilotes: 1.33
  order-time-window: 5

logging:
  level:
    root: info
